### ISSUE TITLE
option for force

### ISSUE THREAD

**Issue by steveoh** [sindresorhus/grunt-eslint#101] opened 2015-12-09 20:15 UTC
what are your thoughts on adding the force option to not fail the grunt task like [jshint](https://github.com/gruntjs/grunt-contrib-jshint#force) and [jscs](https://github.com/jscs-dev/grunt-jscs#force)?

**Comment by sindresorhus** [comment] 2015-12-09 20:33
Duplicate of https://github.com/sindresorhus/grunt-eslint/pull/55.

**Closed by sindresorhus** 2015-12-09 20:33 UTC
