### ISSUE TITLE
SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by Chlodochar** [sindresorhus/grunt-eslint#129] opened 2016-07-30 19:44 UTC
On NodeJS 0.10.36 I get the following warning when running anything with Grunt (where grunt-eslint is 'require'ed):
```
/home/travis/build/AHAAAAAAA/PokemonGo-Map/node_modules/grunt-eslint/tasks/eslint.js:2
const chalk = require('chalk');
^^^^^
Loading "eslint.js" tasks...ERROR
>> SyntaxError: Use of const in strict mode.
```

I realize NodeJS 0.10.36 is old-ish, but Travis is using it by default.

**Comment by sindresorhus** [comment] 2016-07-30 19:58
Duplicate of https://github.com/sindresorhus/grunt-eslint/issues/125.

**Closed by sindresorhus** 2016-07-30 19:58 UTC
