### ISSUE TITLE
force switch needed

### ISSUE THREAD

**Issue by etylsarin** [sindresorhus/grunt-eslint#56] opened 2015-03-09 10:25 UTC
Hi @sindresorhus,

Would it be possible to ad force switch as grunt-contrib-jshint has? I need to report all errors in a file but not fail the task itself.

Thanks,
Filip

**Comment by sindresorhus** [comment] 2015-03-09 10:32
Duplicate of https://github.com/sindresorhus/grunt-eslint/pull/55#issuecomment-77816277

**Closed by sindresorhus** 2015-03-09 10:32 UTC
