### ISSUE TITLE
Errors after Es2015ify

### ISSUE THREAD

**Issue by corneadoug** [sindresorhus/grunt-eslint#126] opened 2016-07-19 08:50 UTC
I get errors and can't run grunt-eslint after [that commit](https://github.com/sindresorhus/grunt-eslint/commit/d0ff94266c668a5d6ad2bfd5bb0e92445f6a580a).
Is there additional configuration to do on grunt side to support es2015?

**Comment by sindresorhus** [comment] 2016-07-19 09:01
Duplicate of https://github.com/sindresorhus/grunt-eslint/issues/125.

**Closed by sindresorhus** 2016-07-19 09:01 UTC
